import os
import html
from pathlib import Path
from datetime import datetime

def get_verdict_color(verdict):
    if verdict == "BULLISH":
        return "#00c853", "🟢"
    elif verdict == "BEARISH":
        return "#d50000", "🔴"
    else:
        return "#ffd600", "🟡"

def generate_report(currency_pair, headlines_data, overall_verdict, summary, low_data_warning=False):
    os.makedirs("reports", exist_ok=True)

    color, emoji = get_verdict_color(overall_verdict)
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    filename_time = datetime.now().strftime("%Y-%m-%d_%H%M")
    pair_clean = currency_pair.replace("/", "")
    filename = f"reports/{pair_clean}_{filename_time}.html"

    warning_html = ""
    if low_data_warning:
        warning_html = f"""
        <div class="warning">
            ⚠️ Low data warning: Only {len(headlines_data)} headlines found after filtering.
            Verdict may not be fully reliable.
        </div>"""

    rows = ""
    for i, h in enumerate(headlines_data, 1):
        s_color, s_emoji = get_verdict_color(h["sentiment"])
        rows += f"""
        <tr>
            <td>{i}</td>
            <td><a href="{html.escape(h['url'])}" target="_blank">{html.escape(h['headline'])}</a></td>
            <td>{html.escape(h['source'])}</td>
            <td style="color:{s_color}; font-weight:600">{s_emoji} {h['sentiment']}</td>
            <td>{round(h['score'], 2)}</td>
            <td>{html.escape(h['reasoning'])}</td>
        </tr>"""

    escaped_summary = html.escape(summary)

    report_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{currency_pair} Sentiment Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #e6edf3; padding: 40px; }}
        .header {{ text-align: center; margin-bottom: 40px; }}
        .header h1 {{ font-size: 2.2rem; color: #58a6ff; letter-spacing: 2px; }}
        .header p {{ color: #8b949e; margin-top: 8px; }}
        .verdict-card {{ background: #161b22; border: 2px solid {color}; border-radius: 12px;
                         padding: 30px; text-align: center; margin-bottom: 30px; }}
        .verdict-label {{ font-size: 1rem; color: #8b949e; text-transform: uppercase; letter-spacing: 2px; }}
        .verdict-value {{ font-size: 3rem; font-weight: 700; color: {color}; margin: 10px 0; }}
        .summary {{ background: #161b22; border-radius: 12px; padding: 24px;
                    margin-bottom: 30px; border-left: 4px solid #58a6ff; }}
        .summary h2 {{ color: #58a6ff; margin-bottom: 12px; font-size: 1rem; text-transform: uppercase; }}
        .summary p {{ line-height: 1.7; color: #c9d1d9; }}
        .warning {{ background: #2d1f00; border: 1px solid #ffd600; border-radius: 8px;
                    padding: 16px; margin-bottom: 24px; color: #ffd600; }}
        table {{ width: 100%; border-collapse: collapse; background: #161b22; border-radius: 12px; overflow: hidden; }}
        th {{ background: #21262d; padding: 14px 16px; text-align: left; color: #8b949e;
              font-size: 0.85rem; text-transform: uppercase; letter-spacing: 1px; }}
        td {{ padding: 14px 16px; border-top: 1px solid #21262d; font-size: 0.9rem; vertical-align: top; }}
        td a {{ color: #58a6ff; text-decoration: none; }}
        td a:hover {{ text-decoration: underline; }}
        tr:hover {{ background: #1c2128; }}
        .footer {{ text-align: center; margin-top: 40px; color: #484f58; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{currency_pair} Sentiment Report</h1>
        <p>{timestamp}</p>
    </div>
    {warning_html}
    <div class="verdict-card">
        <div class="verdict-label">Overall Market Sentiment</div>
        <div class="verdict-value">{emoji} {overall_verdict}</div>
    </div>
    <div class="summary">
        <h2>Analyst Summary</h2>
        <p>{escaped_summary}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Headline</th>
                <th>Source</th>
                <th>Sentiment</th>
                <th>Score</th>
                <th>Reasoning</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    <div class="footer">
        Generated by Sentiment Trader &nbsp;|&nbsp; {timestamp}
    </div>
</body>
</html>"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_html)

    os.startfile(str(Path(filename).resolve()))
    print(f"\n✅ Report saved and opened: {filename}")
    return filename
